### ISSUE TITLE
Consider rename fold to reduce 

### ISSUE THREAD

**Issue by fan-tom** [cuviper/rayon-cond#1]
Both `Iterator` and `ParallelIterator` have `fold` method, but their behavior is very different, because parallel iterator splits input on chunks and calculates `fold` on each chunk, returning multiple results, while serial fold performs "true" folding. The parallel analogue of serial `fold` is `reduce`, and serial iterator has no reduce at all, so no ambiguities are expected.

**Comment by cuviper** [comment]
I don't understand -- we have both `fold` and `reduce` already, following the parallel semantics.

https://github.com/cuviper/rayon-cond/blob/4ea149ae370494beb5212d7246c0b74d2edc3a48/src/lib.rs#L292-L301
https://github.com/cuviper/rayon-cond/blob/4ea149ae370494beb5212d7246c0b74d2edc3a48/src/lib.rs#L313-L328

FWIW, the rayon docs also have a discussion of the different semantics:
https://docs.rs/rayon/1.0.3/rayon/iter/trait.ParallelIterator.html#fold-versus-reduce

**Comment by cuviper** [comment]
Closing, as I believe your question has been answered. Feel free to reopen if you have more to add.
