### ISSUE TITLE
Feature flag for rayon

### ISSUE THREAD

**Issue by bminixhofer** [cuviper/rayon-cond#3]
Hi, thanks for this crate!

I've used it successfully for a while in [nlprule](https://github.com/bminixhofer/nlprule). I now want to make the `rayon` dependency optional to make the dependencies more lightweight.

I think the best solution would be adding a feature `rayon` to the default features in this crate. If the feature is disabled, `CondIterator::new` could always create a serial iterator, independent of the value of `parallel`. This would also benefit other users of this crate (such as [`tokenizers`](https://github.com/huggingface/tokenizers)) where `rayon` is completely optional.

Implementing it would need some refactoring to separate the parallel / serial impls but should be reasonably straightforward unless I'm missing something.

What do you think about this?

**Comment by cuviper** [comment]
Hi!

I'm afraid I don't see an easy way to do this with a feature flag. There are rayon types visible in the return types of most of the methods, as well as in `where` constraints for most of the `impl` blocks. Feature flags are supposed to be purely additive, not making any changes that would be considered breaking the API.

Assuming `rayon` and `rayon-cond` are not visible in your own public API, maybe you can make that optional at your level? That is, you'd write some wrapper of your own that either holds a direct `Iterator` or a `CondIterator` depending on your features.

**Comment by bminixhofer** [comment]
> That is, you'd write some wrapper of your own that either holds a direct Iterator or a CondIterator

The problem here is that I'm using e.g. `find_first` which does not exist on an `Iterator`. This crate already exposes a unified API for parallel and serial iterators so I thought it would be a good place to make the parallel part optional.

> There are rayon types visible in the return types of most of the methods, as well as in where constraints for most of the impl blocks.

Sorry, taking a closer look I see that it's indeed hard to make the feature flag additive in this crate. I think it should be possible, but it's hard for me to say without actually trying to implement it. I might have a go at it. But if it works, it would probably be better off in a separate crate anyway.

Thanks for your response!
