### ISSUE TITLE
Rayon as optional (if default) feature

### ISSUE THREAD

**Issue by clbarnes** [cuviper/rayon-cond#6]
One situation I find myself commonly switching between serial and parallel iterators for is in a library crate where the downstream user may or may not want parallelism and/or the rayon dependency tree. It is possible for developers of those libraries to do their conditional compilation wrappers around whatever functions include calls to rayon-cond, but it might also be convenient to do it at the level of this crate.

I suppose because of trait bounds relying quite heavily on traits from rayon this would probably require pretty much duplicating all the code; if so, probably not worth bothering.

**Comment by cuviper** [comment]
Yeah, there's a similar discussion in #3. I'm afraid it's not possible in the current design. The API would have to treat rayon and an opaque implementation detail to make it work without rayon, and I'm not planning that kind of rewrite.

**Comment by clbarnes** [comment]
Ah, sorry I didn't come across that. Thanks for the quick response!
